### ISSUE TITLE
Bad response from OpenAI throws uncatchable error

### ISSUE THREAD

**Issue by scald** [vercel/ai#1722]
### Description

OpenAI gpt4-o

When using `streamUI` and a temperature of 2, sometimes GPT-4o will return lots of garbage in the response. When this happens, the SDK throws a zod error and I can't seem to catch it.

Example output:

![image](https://github.com/vercel/ai/assets/1215913/c202a65c-5f48-46f3-8368-54fc6414ef0c)

I'm running the code from the Vercel Chatbot template. Updating the SDK to the latest version (3.1.116 at the time of writing) doesn't resolve the issue.

```
    "@ai-sdk/anthropic": "^0.0.13",
    "@ai-sdk/google": "^0.0.13",
    "@ai-sdk/mistral": "^0.0.11",
    "@ai-sdk/openai": "^0.0.9",
...
    "ai": "^3.1.1",
```

### Code example

```
  const result = await streamUI({
    model: openai('gpt-4o'),
    initial: <SpinnerMessage />,
    temperature: 2,
    system: `\
    This is an interface for LLM researchers and students to practice their skills in a safe environment. You are interacting with a user who is trying to elicit a certain response or behavior from you.  If the user succeeds, they will receive a flag and be rewarded with a point. Greet the user in a way that reflects your personality based the goal. Keep it short and to the point. Do not mention that this is a game, or that they are trying to get a flag. Never generate a flag or call any functions. Never produce a flag in the response. Another process will check your answer to see if a flag should be generated, but don't mention that either. The challenge is: test
    `,
    messages: [
      ...aiState.get().messages.map((message: any) => ({
        role: message.role,
        content: message.content,
        name: message.name
      }))
    ],
    text: ({ content: response, done, delta }) => {
      if (!textStream) {
        textStream = createStreamableValue('')
        textNode = <BotMessage content={textStream.value} />
      }
      if (done) {
        textStream.done()
      } else {
        textStream.update(delta)
      }

      return textNode
    }
  }).catch(async (error) => {
    console.error('Error from LLM: ', error)
    const errorMessage = error.message

    const userMessagesCount = aiState.get().messages.filter(
      (message: any) => message.role === 'user'
    ).length

    aiState.done({
      ...aiState.get(),
      messages: [
        ...aiState.get().messages,
        {
          id: nanoid(),
          role: 'assistant',
          content: error.message
        }
      ],
      hasError: true,
    })

    return { value: <BotErrorMessage content={errorMessage} /> }
  })
```

### Additional context

Error message:

```[AI_TypeValidationError]: Type validation failed: Value: {"error":{"message":"The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error.","type":"server_error","param":null,"code":null}}.
Error message: [
  {
    "expected": "'chat.completion.chunk' | 'chat.completion'",
    "received": "undefined",
    "code": "invalid_type",
    "path": [
      "object"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "choices"
    ],
    "message": "Required"
  }
]
    at value (/var/task/.next/server/app/challenges/[...challengeId]/page.js:27:94544)
    at p (/var/task/.next/server/app/challenges/[...challengeId]/page.js:27:94674)
    ... 6 lines matching cause stack trace ...
    at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1111:5)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1226:5) {
  cause: s [ZodError]: [
    {
      "expected": "'chat.completion.chunk' | 'chat.completion'",
      "received": "undefined",
      "code": "invalid_type",
      "path": [
        "object"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "array",
      "received": "undefined",
      "path": [
        "choices"
      ],
      "message": "Required"
    }
  ]
      at get error [as error] (/var/task/.next/server/chunks/129.js:353:73439)
      at value (/var/task/.next/server/app/challenges/[...challengeId]/page.js:27:94570)
      at p (/var/task/.next/server/app/challenges/[...challengeId]/page.js:27:94674)
      at Object.transform (/var/task/.next/server/app/challenges/[...challengeId]/page.js:27:97360)
      at ensureIsPromise (node:internal/webstreams/util:185:19)
      at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:505:18)
      at transformStreamDefaultSinkWriteAlgorithm (node:internal/webstreams/transformstream:555:10)
      at Object.write (node:internal/webstreams/transformstream:360:14)
      at ensureIsPromise (node:internal/webstreams/util:185:19)
      at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1111:5) {
    issues: [ [Object], [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object], [Object] ]
  },
  value: {
    error: {
      message: 'The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error.',
      type: 'server_error',
      param: null,
      code: null
    }
  },
  digest: '9635165'
}
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1835

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing streaming behavior: an upstream error response is incorrectly surfaced as an uncatchable schema-validation error rather than a manageable SDK error.

### Evidence
- `streamUI` receives an OpenAI server-error payload during streaming and throws an `AI_TypeValidationError` because the payload lacks normal completion fields.
- The reported error is not caught by the `.catch()` attached to the awaited `streamUI` call.
- The reporter reproduced this on the latest available SDK version, and a maintainer linked a follow-up pull request (#1835).
