### ISSUE TITLE
AI SDK 3.1 not working with Remix

### ISSUE THREAD

**Issue by wong2** [vercel/ai#1730]
### Description

Upgraded from 3.0 to 3.1 for my Remix application, the following error occurs:

```
APICallError [AI_APICallError]: Failed to process successful response
    at postToApi (file:///Users/wong2/codes/projects/chathub-monorepo/node_modules/.pnpm/@ai-sdk+provider-utils@0.0.11_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:302:13)
......
......
{
  url: 'https://api.openai.com/v1/chat/completions',
  requestBodyValues: {
    model: 'gpt-4o',
    logit_bias: undefined,
    logprobs: false,
    top_logprobs: undefined,
    user: undefined,
    max_tokens: undefined,
    temperature: 0,
    top_p: undefined,
    frequency_penalty: undefined,
    presence_penalty: undefined,
    seed: undefined,
    messages: [ [Object], [Object] ],
    tools: undefined,
    tool_choice: undefined,
    stream: true,
    stream_options: { include_usage: true }
  },
  statusCode: 200,
  responseHeaders: {
    ...
  },
  responseBody: undefined,
  cause: TypeError: First parameter has member 'readable' that is not a ReadableStream.
      at assertReadableStream (/Users/wong2/codes/projects/chathub-monorepo/node_modules/.pnpm/web-streams-polyfill@3.3.3/node_modules/web-streams-polyfill/dist/ponyfill.js:466:19)
      at convertReadableWritablePair (/Users/wong2/codes/projects/chathub-monorepo/node_modules/.pnpm/web-streams-polyfill@3.3.3/node_modules/web-streams-polyfill/dist/ponyfill.js:4035:9)
      at ReadableStream.pipeThrough (/Users/wong2/codes/projects/chathub-monorepo/node_modules/.pnpm/web-streams-polyfill@3.3.3/node_modules/web-streams-polyfill/dist/ponyfill.js:4119:29)
      at file:///Users/wong2/codes/projects/chathub-monorepo/node_modules/.pnpm/@ai-sdk+provider-utils@0.0.11_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:398:26
      at postToApi (file:///Users/wong2/codes/projects/chathub-monorepo/node_modules/.pnpm/@ai-sdk+provider-utils@0.0.11_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:291:20)
```

### Code example

```
import { createOpenAI } from '@ai-sdk/openai'

const openai = createOpenAI({
  apiKey: 'sk-xxxxxxx',
})

export const action: ActionFunction = async ({ request }) => {
	const model = aihubmix.chat('gpt-4o')
    const result = await streamText({
      model,
      messages,
      abortSignal: request.signal,
    })
	// error before reaching here
    for await (const textPart of result.textStream) {
      console.log(textPart)
    }
    return result.toAIStreamResponse({})
}
```

**Comment by wong2** [comment]
Seems to be a Remix issue, I'll close this.

Related: https://github.com/remix-run/remix/discussions/9389

**Comment by remorses** [comment]
Why is AI sdk using [web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill)? 

That package seems to do some weird stuff like checking for a `_readableStreamController` field to know if an object is a readable stream

https://github.com/MattiasBuelens/web-streams-polyfill/blob/f32598d6db7376dfa61f644d06ce7f6f19a09314/src/lib/readable-stream.ts#L440

**Comment by lgrammel** [comment]
@remorses where do we use that?

**Comment by remorses** [comment]
Sorry my mistake, it's actually @remix-run/dev using it

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The comments supersede the initial attribution and identify the failure as originating from Remix tooling rather than broken AI SDK behavior, so this is not an actionable AI SDK bug or feature request.

### Evidence
- The initial report shows a stream interoperability error after upgrading AI SDK from 3.0 to 3.1 in a Remix application.
- The reporter later concluded, “Seems to be a Remix issue,” and closed the issue.
- A later commenter confirmed that `web-streams-polyfill`, implicated in the error, was used by `@remix-run/dev`, not the AI SDK.
