### ISSUE TITLE
Ungraceful failure error when the anthropic api is overloaded

### ISSUE THREAD

**Issue by TechNickAI** [vercel/ai#2453]
### Description

When anthropic api is busy/down, it responds with 

{"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"}}

Which causes an unhandled rejection 

unhandledRejection: TypeValidationError [AI_TypeValidationError]: Type validation failed: Value: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"}}.
Error message: [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "message_start",
      "content_block_start",
      "content_block_delta",
      "content_block_stop",
      "message_delta",
      "message_stop",
      "ping"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'message_start' | 'content_block_start' | 'content_block_delta' | 'content_block_stop' | 'message_delta' | 'message_stop' | 'ping'"
  }
]
    at safeValidateTypes (/Users/nick/src/cora-morphic/.next/server/chunks/ssr/node_modules_d8329a._.js:2811:20)
    at safeParseJSON (/Users/nick/src/cora-morphic/.next/server/chunks/ssr/node_modules_d8329a._.js:2856:16)
    ... 5 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ZodError: [
    {
      "code": "invalid_union_discriminator",
      "options": [
        "message_start",
        "content_block_start",
        "content_block_delta",
        "content_block_stop",
        "message_delta",
        "message_stop",
        "ping"
      ],
      "path": [
        "type"
      ],
      "message": "Invalid discriminator value. Expected 'message_start' | 'content_block_start' | 'content_block_delta' | 'content_block_stop' | 'message_delta' | 'message_stop' | 'ping'"
    }
  ]
      at get error (/Users/nick/src/cora-morphic/.next/server/chunks/ssr/node_modules_zod_lib_index_mjs_8e7072._.js:665:31)
      at safeValidateTypes (/Users/nick/src/cora-morphic/.next/server/chunks/ssr/node_modules_d8329a._.js:2813:41)
      at safeParseJSON (/Users/nick/src/cora-morphic/.next/server/chunks/ssr/node_modules_d8329a._.js:2856:16)
      at Object.transform (/Users/nick/src/cora-morphic/.next/server/chunks/ssr/node_modules_d8329a._.js:3033:40)
      at invokePromiseCallback (node:internal/webstreams/util:180:10)
      at Object.<anonymous> (node:internal/webstreams/util:185:23)
      at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:526:37)
      at node:internal/webstreams/transformstream:567:16
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    issues: [ [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object] ]
  },
  value: {
    type: 'error',
    error: { details: null, type: 'overloaded_error', message: 'Overloaded' }
  }
}

**Comment by arnab710** [comment]
Same issue here.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2457

**Comment by lgrammel** [comment]
Resolved in `@ai-sdk/anthropic@0.0.34`

**Comment by raulgupta** [comment]
{"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"}              }

**Comment by lgrammel** [comment]
@raulgupta on which version of the anthropic provider did this happen for you?

**Comment by mtrazzi** [comment]
happening with claude code

**Comment by addmorebass** [comment]
Fix your servers, Anthropic!!

**Comment by cacoos** [comment]
This is happening frequently, and setting `maxRetries` does not trigger a retry.

I'm happy to help contribute a fix. I understand that errors during streaming should generally be raised rather than retried, but perhaps we should maintain a list of exceptions that should be retried?

In particular, I’d like to retry `Overloaded`.

**Comment by blackge** [comment]
Has anyone got a workaround for this one? It basically makes using Anthropic with the AI SDK unusable. I'm getting this error on about 30-40% of requests at the moment.

BTW I agree with @addmorebass that this is really for Anthropic to fix their servers. I guess they are using it to force more people onto the Enterprise plans.

**Comment by rpenchalaLFT** [comment]
same here 

Malformed JSON sent from server: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"} }

**Comment by addmorebass** [comment]
@blackge I'm considering a change to Gemini because the rate limits aren't very generous and quality in my evals has gone down.

**Comment by thdxr** [comment]
the root issue here is that the errors aren't retrying - was poking around and couldn't find exactly why that's the case.

customizing retry logic is probably the most useful thing

**Comment by lgrammel** [comment]
I've investigated this further and added test cases to verify the AI SDK Anthropic provider handles the errors correctly.

I suspect the reason is that Anthropic can stream those errors in the middle of the stream, after content has been sent:

https://docs.anthropic.com/en/docs/build-with-claude/streaming#error-events

Because content may already have been sent at this point, any retries are application dependent and may require invalidating content that has already been sent. My suggestion would be to listen for these specific errors in the stream and remove the whole assistant response in the ui / from the messages when they come up. My hope would be that Anthropic would send 529 responses instead of breaking mid-stream with those errors.

**Comment by thdxr** [comment]
^ yep i finally was able to capture them


```
HTTP/1.1 200 OK
access-control-allow-headers: Content-Type, Authorization, ai-gateway-auth-method, ai-gateway-protocol-version, ai-model-id, ai-language-model-id, ai-language-model-specification-version, ai-language-model-streaming
access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin: *
cache-control: public, max-age=0, must-revalidate
date: Fri, 25 Jul 2025 15:26:29 GMT
server: Vercel
strict-transport-security: max-age=63072000; includeSubDomains; preload
transfer-encoding: chunked
x-matched-path: /v1/ai/language-model
x-vercel-cache: MISS
x-vercel-id: iad1::iad1::n4lpg-1753457188736-f2750671afdb

data: {"type":"stream-start","warnings":[]}

data: {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}

DONE
```

**Comment by nneven** [comment]
Switching to AI Gateway and/or OpenRouter should also be a workaround to using Claude reliably, if I'm not mistaken?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete provider failure when handling a valid Anthropic error event, and the maintainer confirmed a released fix. This is a bug even though later discussion also requests customized retry behavior.

### Evidence
- Anthropic's streamed `overloaded_error` was rejected by the provider schema, causing an unhandled `TypeValidationError`.
- A maintainer linked PR #2457 and stated the issue was resolved in `@ai-sdk/anthropic@0.0.34`.
- Later reports distinguish mid-stream overload errors, which cannot always be safely retried after content has already been emitted.
