### ISSUE TITLE
AI_TypeValidationError error with streamText().toAIStream()

### ISSUE THREAD

**Issue by marclelamy** [vercel/ai#2656]
### Description

When running models like llama or mistral, I'm getting the type validation error but it's not always happening, sometimes the completion runs just fine. 
In the code below, I see the onStart() log and the error happens right after and the first token doesn't get looged

### Code example

```ts
// Setting stream value
const stream = createStreamableValue('');

const result = await streamText({
    model: client(selectedModel.providerModelId as string),
    messages: messages as any[],
    },
});


// process stream
let firstToken: any = undefined
result.toAIStream({
    onStart: () => {
        console.log('start to init time in ms', new Date().getTime() - initTime.getTime())
        logs.logNewEvent('OAI stream started')
    },
    onToken: (token) => {
        if (firstToken === undefined) {
            firstToken = token
            console.log('first token to init time in ms', new Date().getTime() - initTime.getTime()) 
        }
    }
});


// Send each chunk one by one to the client
for await (const delta of result.textStream) {
    stream.update(delta);
}


// close stream
stream.done();
```

**Comment by lgrammel** [comment]
This can happen when the model returns responses they do not match the schema. Those providers do not have grammar-guided generation (aka structured outputs) yet. In the meantime, you can improve your result with prompting, see e.g. the following tips:

- https://sdk.vercel.ai/docs/ai-sdk-core/generating-structured-data#schema-writing-tips
- https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#prompt-engineering-with-tools

**Comment by lgrammel** [comment]
@marclelamy can you post the details of the error that you are seeing (from the console/terminal)?

**Comment by marclelamy** [comment]
Oh my bad I forgot to paste it. 
```
Unhandled Rejection: u [AI_TypeValidationError]: Type validation failed: Value: {"id":"gen-lp658zQbL7YL6jCo6i3lEFrScqa6","model":"meta-llama/llama-3.1-8b-instruct","object":"chat.completion.chunk","created":1723594224,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null,"logprobs":{"tokens":null,"token_logprobs":null,"top_logprobs":null,"text_offset":null}}]}.
Error message: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "array",
            "received": "undefined",
            "path": [
              "choices",
              0,
              "logprobs",
              "content"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "error"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]
    at s (/var/task/.next/server/app/page.js:191:7946)
    at o (/var/task/.next/server/app/page.js:191:8223)
    ... 5 lines matching cause stack trace ...
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1109:5)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1224:5) {
  cause: t [ZodError]: [
    {
      "code": "invalid_union",
      "unionErrors": [
        {
          "issues": [
            {
              "code": "invalid_type",
              "expected": "array",
              "received": "undefined",
              "path": [
                "choices",
                0,
                "logprobs",
                "content"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "code": "invalid_type",
              "expected": "object",
              "received": "undefined",
              "path": [
                "error"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        }
      ],
      "path": [],
      "message": "Invalid input"
    }
  ]
      at get error [as error] (/var/task/.next/server/app/page.js:204:83823)
      at Object.validate (/var/task/.next/server/app/page.js:191:7820)
      at s (/var/task/.next/server/app/page.js:191:7888)
      at o (/var/task/.next/server/app/page.js:191:8223)
      at Object.transform (/var/task/.next/server/app/page.js:191:11245)
      at ensureIsPromise (node:internal/webstreams/util:192:19)
      at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:505:18)
      at transformStreamDefaultSinkWriteAlgorithm (node:internal/webstreams/transformstream:555:10)
      at Object.write (node:internal/webstreams/transformstream:360:14)
      at ensureIsPromise (node:internal/webstreams/util:192:19) {
    issues: [ [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object] ]
  },
  value: {
    id: 'gen-lp658zQbL7YL6jCo6i3lEFrScqa6',
    model: 'meta-llama/llama-3.1-8b-instruct',
    object: 'chat.completion.chunk',
    created: 1723594224,
    choices: [ [Object] ]
  }
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

**Comment by marclelamy** [comment]
@lgrammel

**Comment by lgrammel** [comment]
it seems that the an error response chunk is incorrectly parsed. this is provider specific.

which provider are you using? can you add your provider initialization code (in particular if you are using the openai provider with a non-openai service)?

**Comment by marclelamy** [comment]
@lgrammel For non OpenAI/Perplexity models I'm using [OpenRouter](https://openrouter.ai).


Here's most of the code. The strange thing is that the error doesn't get caught in the try/catch. What better way should I implement to fix/catch that?

```tsx
'use server';

import { streamText } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { FormattedRequestObject, User } from "@/lib/types"



// instantiating clients 
const openaiClient = createOpenAI({
    apiKey: process.env.OPENAI_API_KEY || "",
})

const openrouterClient = createOpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY || "",
    headers: {
        "HTTP-Referer": "tryblend.ai",
        "X-Title": "blendai",
    },
})

const perplexityClient = createOpenAI({
    apiKey: process.env.PERPLEXITY_API_KEY || "",
    baseURL: "https://api.perplexity.ai",
})




// specify type returned from openai
export async function generate(data: FormattedRequestObject): Promise<any> {
    // does some pre request stuff


    // Setting stream value
    const stream = createStreamableValue('');

    const processStream = async () => {
        // setting client based on model provider
        let client
        if (selectedModel.provider === "openai") {
            client = openaiClient
        } else if (selectedModel.provider === "openrouter") {
            client = openrouterClient
        } else if (selectedModel.provider === "perplexity") {
            client = perplexityClient
        } else {
            return { error: "Invalid model provider" }
        }


        // Run model
        let error: any = false
        const result = await streamText({
            model: client(selectedModel.providerModelId as string),
            messages: messages as any[],
            onFinish: async (final) => {
                // does some other stuff
            }
        });


        // process stream
        let firstToken: any = undefined
        result.toAIStream({
            onStart: () => {
                console.log('on start')
            },
            onToken: (token) => {
                if (firstToken === undefined) {
                    firstToken = token
                    console.log('on token')
                }
            },
        });


        // Send each chunk one by one to the client
        for await (const delta of result.textStream) {
            stream.update(delta);
        }


        // close stream
        stream.done();
    };


    // process stream
    try {
        processStream();
    } catch (error: any) {
        return { error: {message: error.message, status: error.status} }
    }

    return { output: stream.value }
}
```

**Comment by mirkonasato** [comment]
Had a similar issue when calling a local [mlx-lm server](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md), however it was resolved by switching to the [@ai-sdk/openai-compatible](https://sdk.vercel.ai/providers/openai-compatible-providers) provider rather than `@ai-sdk/openai`.

**Comment by aayush-kapoor** [comment]
Marking this as closed for now - if you face any regression or have a similar problem after migrating to the latest AI SDK version, please feel free to open a new issue (with possible reproduction)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete runtime validation failure while processing streamed output through the SDK. Although using the OpenAI-compatible provider may avoid it, the reported behavior is an unexpected parsing failure rather than a request for new functionality.

### Evidence
- Streaming OpenRouter llama/mistral responses intermittently throws AI_TypeValidationError before the first token.
- The supplied chunk contains a logprobs shape that fails the OpenAI provider schema, which expects choices[0].logprobs.content.
- A maintainer stated that an error response chunk appeared to be incorrectly parsed and that the behavior was provider-specific.
