### ISSUE TITLE
Bedrock client does not work natively with profiles, instance roles, container roles, etc.

### ISSUE THREAD

**Issue by mrburrito** [vercel/ai#2780]
### Description

The Bedrock provider currently requires explicitly defining either the AWS credentials or the environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and (optionally) `AWS_SESSION_TOKEN` when using `createAmazonBedrock()` instead of relying on Amazon's internal credential chains. This makes it nearly impossible to use with assumed roles through SSO profiles, instance roles, or container roles in ECS or EKS since those variables would have to be defined, and then updated, at runtime.

Instead of forcing a lookup from `process.env` in the options, and failing if undefined, pass those through to the `BedrockRuntimeClient` and let it handle credential resolution natively. It will use those values if you provide them, falling back to the `AWS_*` environment variables, then `AWS_PROFILE`, then container role lookup, then instance role lookup, then failure.

### Expected Behavior

The Bedrock provider uses AWS' native credential chain to resolve access from any supported credential provider, calls Bedrock, and returns the response from the model.

### Actual Behavior

`bedrock` and `createAmazonBedrock` functions throw an exception if credentials are not explicitly provided using environment variables or the options object.

### Code example

```
import { bedrock } from '@ai-sdk/amazon-bedrock';
import {
  BedrockRuntimeClient,
  InvokeModelCommand,
} from '@aws-sdk/client-bedrock-runtime';

async function vercelAi() {
  try {
    const { text } = await generateText({
      model: bedrock('anthropic.claude-3-5-sonnet-20240620-v1:0'),
      prompt:
        'Please explain the order in which the default AWS Credential Chain looks up credentials.',
    });
    console.log(text);
  } catch (e) {
    console.error(e);
  }
}

async function nativeBedrock() {
  const client = new BedrockRuntimeClient();
  const payload = {
    anthropic_version: 'bedrock-2023-05-31',
    max_tokens: 4096,
    messages: [
      {
        role: 'user',
        content: [
          {
            type: 'text',
            text: 'Please explain the order in which the default AWS Credential Chain looks up credentials.',
          },
        ],
      },
    ],
  };
  const command = new InvokeModelCommand({
    modelId: 'anthropic.claude-3-5-sonnet-20240620-v1:0',
    body: JSON.stringify(payload),
  });

  try {
    const response = await client.send(command);
    const decodedResponseBody = new TextDecoder().decode(response.body);
    const responseBody = JSON.parse(decodedResponseBody);
    console.log(responseBody.content[0].text);
  } catch (e) {
    console.error(e);
  }
}

await vercelAi();
console.log('\n----------\n');
await nativeBedrock();
```

#### Output

```
LoadSettingError [AI_LoadSettingError]: AWS access key ID setting is missing. Pass it using the 'accessKeyId' parameter or the AWS_ACCESS_KEY_ID environment variable.
    at loadSetting (webpack-internal:///(rsc)/./node_modules/@ai-sdk/amazon-bedrock/node_modules/@ai-sdk/provider-utils/dist/index.mjs:170:11)
    at createBedrockRuntimeClient (webpack-internal:///(rsc)/./node_modules/@ai-sdk/amazon-bedrock/dist/index.mjs:444:91)
    at createChatModel (webpack-internal:///(rsc)/./node_modules/@ai-sdk/amazon-bedrock/dist/index.mjs:465:13)
    at provider (webpack-internal:///(rsc)/./node_modules/@ai-sdk/amazon-bedrock/dist/index.mjs:474:12)
    at vercelAi (webpack-internal:///(rsc)/./src/app/api/chats/[id]/entries/route.ts:39:83)
    at POST (webpack-internal:///(rsc)/./src/app/api/chats/[id]/entries/route.ts:104:15)
    at replacement (webpack-internal:///(rsc)/./src/lib/response-helpers.ts:37:41)
    at async replacement (webpack-internal:///(rsc)/./src/lib/response-helpers.ts:54:24)
    at async <redacted> {
  cause: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_LoadSettingError)]: true
}

----------

The AWS SDK uses a credential provider chain to look for AWS credentials in a particular order. This chain is designed to find credentials in the most secure and convenient locations first. Here's the order in which the default AWS Credential Chain looks up credentials:

1. Environment Variables:
   The SDK first checks for credentials in your system's environment variables:
   - AWS_ACCESS_KEY_ID
   - AWS_SECRET_ACCESS_KEY
   - AWS_SESSION_TOKEN (if using temporary credentials)

2. Java System Properties:
   If environment variables are not set, it looks for Java system properties:
   - aws.accessKeyId
   - aws.secretKey

3. AWS Credentials file:
   The SDK then checks for a credentials file located at ~/.aws/credentials (Linux/Mac) or C:\Users\USERNAME\.aws\credentials (Windows).

4. AWS Config file:
   If credentials are not found in the credentials file, it checks the AWS config file at ~/.aws/config (Linux/Mac) or C:\Users\USERNAME\.aws\config (Windows).

5. Container credentials:
   For applications running on ECS (Elastic Container Service), the SDK checks for credentials in the Amazon ECS container credentials provider.

6. Instance profile credentials:
   For applications running on EC2 instances, the SDK checks the instance metadata service for credentials associated with the EC2 instance's IAM role.

7. Web Identity Token credentials:
   For applications using web identity federation, the SDK checks for credentials from the AWS Security Token Service (STS) using a web identity token.

The SDK stops searching as soon as it finds credentials in one of these locations. If no credentials are found after checking all these locations, the SDK will throw an exception.

It's important to note that this order can be customized or overridden by explicitly specifying a credentials provider or by creating a custom credentials provider chain. Additionally, the exact order and available options might vary slightly depending on the specific AWS SDK and its version.
```

### Additional context

I'm running the code above with `AWS_REGION=us-east-1` and an assumed role via SSO. In practice, I'll provide the region at runtime depending on the target model, but my system will always be using temporary credentials. I have not deployed this to our EKS cluster yet, but expect to see the same failure since those environment variables aren't set. I'll update the ticket to confirm once those are set.

**Comment by mrburrito** [comment]
I started working on a PR to fix this problem and, as I was updating the documentation, discovered that the default provider chain won't run in browser, which would likely break things for anyone using this library in a client side component.

In reading AWS' documentation on the [Node Credential Providers](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/#fromNodeProviderChain), I realized there is a simple workaround to support any authentication needs using the `options.bedrockOptions.credentials` configuration. For anyone else that runs across this issue, here's a code snippet that is working perfectly for our server-side execution:

```typescript
import { generateText } from 'ai';
import { createAmazonBedrock } from '@ai-sdk/amazon-bedrock';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';

const bedrock = createAmazonBedrock({
  bedrockOptions: {
    region: 'us-east-1',
    // tells BedrockRuntimeClient to use the default NodeJS provider chain, which will
    // load AWS profiles, Container Roles, Instance Roles, etc.
    credentials: fromNodeProviderChain(),
  },
});

const { text } = await generateText({
  model: bedrock('anthropic.claude-3-5-sonnet-20240620-v1:0'),
  prompt: 'Please explain the order in which the default AWS Credential Chain looks up credentials.',
});
console.log(text);
```

**Comment by daohoangson** [comment]
Since `@ai-sdk/amazon-bedrock` v2, this is no longer possible. I had to downgrade back to v1.1.6 to restore access for AWS_PROFILE.

**Comment by lgrammel** [comment]
cc @shaper

**Comment by shaper** [comment]
> Since `@ai-sdk/amazon-bedrock` v2, this is no longer possible. I had to downgrade back to v1.1.6 to restore access for AWS_PROFILE.

@daohoangson Hi, looking into this. In case it helps us get things back in action for v2 for you sooner, can you provide more specifics on exactly which step/source for credentials you are using? What kind of credentials and where are they placed, what are the file/key names, do you have any role complexity considerations.

And to be explicit, you have been relying on https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/Variable/fromNodeProviderChain/ to date, correct?

**Comment by niraj-at-travelopia** [comment]
I am facing the same issue, I want to get this working using IAM roles

**Comment by EgorKrasno** [comment]
Same issue, v2 no longer picks up AWS_PROFILE credentials.

**Comment by shaper** [comment]
Brief update - working on this, goal is to show how you can achieve similar functionality to what you were doing before. Thanks for the details, as others may find this issue, please add your specifics/use case details as well, it is helpful.

**Comment by shaper** [comment]
Hi folks, I think we can still use a similar approach to the one described above that you've been using to date. See revised example below. Please try this out and let me know how it works for you.

```
import { createAmazonBedrock } from '@ai-sdk/amazon-bedrock';
import { generateText } from 'ai';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';

async function main() {
  const credentialsProvider = fromNodeProviderChain();
  const credentials = await credentialsProvider();
  const bedrock = createAmazonBedrock({
    region: 'us-east-2',
    ...credentials,
  });

  const { text } = await generateText({
    model: bedrock('anthropic.claude-3-5-sonnet-20240620-v1:0'),
    prompt: 'Invent a new holiday and describe its traditions.',
  });

  console.log(text);
}

main().catch(console.error);
```

**Comment by daohoangson** [comment]
I tried @shaper suggestion and it works with our `aws sso login` workflow. A few notes:

- Creating a model is now asynchronous
- The `credentials` is regenerated each time with a 1 hour TTL so some caching logic is probably needed, at least for the SSO. Unsure about other mechanism supported by `fromNodeProviderChain`

**Comment by rfsmart-eland** [comment]
I tried to make the sample code provided above modular and have one file initialize the client to call elsewhere in my project, which I think is a common enough practice.

My maybe simpliest iteration looks liked:

```"use server"
import { createAmazonBedrock } from '@ai-sdk/amazon-bedrock';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';

export async function getBedrockClient() {
  const credentialsProvider = fromNodeProviderChain();
  const credentials = await credentialsProvider();
  
  return createAmazonBedrock({
    region: 'us-east-2',
    ...credentials,
  });
}

// Export a function that gets a specific model
export async function getBedrockModel(modelId: string) {
  const client = await getBedrockClient();
  return client(modelId);
} ```

Using it like:
```"use server";

import { generateText } from "ai";
import { getBedrockModel } from "../bedrock/aisdkClient";

const model = await getBedrockModel('anthropic.claude-3-7-sonnet-20250219-v1:0');

  const { text } = await generateText({
    model: bedrock('anthropic.claude-3-5-sonnet-20240620-v1:0'),
    prompt: 'Invent a new holiday and describe its traditions.',
  });

  console.log(text);
```

and would get 
>  ⨯ CredentialsProviderError: Could not load credentials from any providers
    at async getBedrockClient (./src/server/bedrock/aisdkClient.ts:19:25)
    at async getBedrockModel (./src/server/bedrock/aisdkClient.ts:27:20)
    at async eval (./src/server/chat/nameChat.ts:17:15)

**Comment by niranjan94** [comment]
@shaper though your suggestion works, it makes the behavior of the bedrock provider different from every other providers. The provider creation has to be done asynchronously. And the provider has to be created every-time a model from bedrock has to be invoked (since the credentials on AWS can be short-lived).

I have taken a stab at fixing it in a way the bedrock provider can be used similar to any other AWS SDK, without adding any dependency to the provider itself and without the usage behavior changing (provider creation need not be async. provider just has to be created once)

https://github.com/vercel/ai/pull/5220

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete provider failure affecting standard AWS credential resolution, including a reported v2 regression, rather than merely a request for documentation or a new example.

### Evidence
- The Bedrock provider throws AI_LoadSettingError unless access keys are explicitly supplied, instead of allowing the AWS SDK credential provider chain to resolve profiles or IAM roles.
- Multiple commenters report that v2 no longer accepts the prior fromNodeProviderChain integration or AWS_PROFILE credentials, requiring a downgrade or manual credential resolution.
- The maintainer-provided workaround works for SSO but requires asynchronous provider creation and does not naturally refresh short-lived credentials; a PR was opened to restore native AWS SDK-like behavior.
