### ISSUE TITLE
StreamUI unhandledRejection: Error: .update(): UI stream is already closed.

### ISSUE THREAD

**Issue by ifreeman6** [vercel/ai#3007]
### Description

The StreamUI calling tool reports an error, but the normal output components:

Error: .update(): UI stream is already closed.
    at assertStream (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12394:19)
    at Object.update (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12412:13)
    at handleRender (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12830:21)
    at G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12870:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ⨯ unhandledRejection: Error: .update(): UI stream is already closed.
    at assertStream (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12394:19)
    at Object.update (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12412:13)
    at handleRender (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12830:21)
    at G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12870:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ⨯ unhandledRejection: Error: .update(): UI stream is already closed.
    at assertStream (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12394:19)
    at Object.update (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12412:13)
    at handleRender (G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12830:21)
    at G:\ai-project\ai-chatbot\.next\server\chunks\ssr\_39f80c._.js:12870:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by lgrammel** [comment]
This happens when `close()` has been called on a streamableUI already, e.g. when you have parallel tool calls. `streamUI` uses this internally, so the cause can be parallel tool calls by the AI.

First try to turn off parallel tool calls (especially w/ openai - see OpenAI provider https://sdk.vercel.ai/providers/ai-sdk-providers/openai ). If that is not sufficient, you can use `streamText` with your own `createStreamableUI` instance to have more control, or switch to AI SDK UI.

**Comment by sylviangth** [comment]
> This happens when `close()` has been called on a streamableUI already, e.g. when you have parallel tool calls. `streamUI` uses this internally, so the cause can be parallel tool calls by the AI.
> 
> First try to turn off parallel tool calls (especially w/ openai - see OpenAI provider https://sdk.vercel.ai/providers/ai-sdk-providers/openai ). If that is not sufficient, you can use `streamText` with your own `createStreamableUI` instance to have more control, or switch to AI SDK UI.

@lgrammel How can I turn off parallelToolCalls with createOpenAI? I tried this but it says 'parallelToolCalls' does not exist in type 'OpenAICompletionSettings'

<img width="342" alt="image" src="https://github.com/user-attachments/assets/0d7edf1d-a1ae-4241-87f1-c7da70064eab">

**Comment by lgrammel** [comment]
It is available when you use chat models (completion models don't support tool calls to begin with): https://sdk.vercel.ai/providers/ai-sdk-providers/openai#chat-models

**Comment by ifreeman6** [comment]
> This happens when `close()` has been called on a streamableUI already, e.g. when you have parallel tool calls. `streamUI` uses this internally, so the cause can be parallel tool calls by the AI.
> 
> First try to turn off parallel tool calls (especially w/ openai - see OpenAI provider https://sdk.vercel.ai/providers/ai-sdk-providers/openai ). If that is not sufficient, you can use `streamText` with your own `createStreamableUI` instance to have more control, or switch to AI SDK UI.

It's not okey when I turn off the "parallelToolCalls" config, the error occurs as before.
```js
const openai = createOpenAI({
  baseURL: process.env.OPENAI_API_BASE,
  apiKey: process.env.OPENAI_API_KEY,
})
let openaiApiModel = process.env.OPENAI_API_MODEL || 'gpt-4o'
let model = openai.chat(openaiApiModel, {
  parallelToolCalls: false
})
```

**Comment by ifreeman6** [comment]
I think this is a bug. Please fix it in the next version.

**Comment by ifreeman6** [comment]
When i upgrade the latest version of ai, the bug still exists.

**Comment by aaron5670** [comment]
Same issue here.

**Comment by aayush-kapoor** [comment]
Marking this as closed for now - if you face any regression or have a similar problem after migrating to the latest AI SDK version, please feel free to open a new issue (with possible reproduction)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete runtime failure in existing `streamUI` behavior, with an unhandled rejection caused by updating a closed UI stream. Suggested workarounds do not change that this is broken current behavior.

### Evidence
- `streamUI` throws an unhandled rejection: `.update(): UI stream is already closed` during tool calls.
- A maintainer confirmed the error occurs when `streamUI` attempts to update an internally closed `streamableUI`, including with parallel tool calls.
- A reporter stated that disabling `parallelToolCalls` did not resolve the failure, and multiple users confirmed it persisted across SDK versions.
