### ISSUE TITLE
use createOpenAI with deepseek get errors 'Cannot connect to API: Connect Timeout Error'

### ISSUE THREAD

**Issue by kaifengwang-sbi-dalian** [vercel/ai#3224]
### Description

I plan to create a basic streaming conversation with deepseek api base on the example( https://github.com/vercel/ai/blob/main/examples/ai-core/src/generate-text/deepseek.ts ), but got the error as below, even if use the mistral, also got the same error message, it may be an issue with the network proxy, but I have no idea how to fix it.
What do I need to do to solve this problem? thanks a lot.

### Code example

```
import { createOpenAI } from "@ai-sdk/openai";
import { streamText, convertToCoreMessages } from "ai";

const deepSeek = createOpenAI({
  baseURL: "https://api.deepseek.com",
  apiKey: 'my deepseek api key',
});

export const maxDuration = 30;

export async function POST(req: Request) {
  const { messages } = await req.json();

  const result = await streamText({
    model: deepSeek("deepseek-chat"),
    messages: convertToCoreMessages(messages),
    maxRetries: 0,
  });

  return result.toDataStreamResponse();
}
```

### Additional context

error message

```
APICallError [AI_APICallError]: Cannot connect to API: Connect Timeout Error
    at postToApi (webpack-internal:///(rsc)/./node_modules/@ai-sdk/provider-utils/dist/index.mjs:418:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIChatLanguageModel.doStream (webpack-internal:///(rsc)/./node_modules/@ai-sdk/openai/dist/index.mjs:409:50)
    at async fn (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:3876:23)
    at async eval (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:334:22)
    at async _retryWithExponentialBackoff (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:164:12)
    at async startStep (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:3841:13)
    at async fn (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:3915:11)
    at async eval (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:334:22)
    at async POST (webpack-internal:///(rsc)/./src/app/api/chat/route.ts:44:20)
    at async C:\project\file-insight-web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55759
    at async eO.execute (C:\project\file-insight-web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
    at async eO.handle (C:\project\file-insight-web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57093)
    at async doRender (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:1345:42)
    at async cacheEntry.responseCache.get.routeKind (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:1939:32)
    at async DevServer.pipeImpl (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\project\file-insight-web\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\project\file-insight-web\node_modules\next\dist\server\base-server.js:810:17)
    at async C:\project\file-insight-web\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\project\file-insight-web\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\project\file-insight-web\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\project\file-insight-web\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\project\file-insight-web\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\project\file-insight-web\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\project\file-insight-web\node_modules\next\dist\server\lib\start-server.js:141:13) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
      at node:internal/deps/undici/undici:6587:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  },
  url: 'https://api.deepseek.com/chat/completions',
  requestBodyValues: {
    model: 'deepseek-chat',
    logit_bias: undefined,
    logprobs: undefined,
    top_logprobs: undefined,
    user: undefined,
    parallel_tool_calls: undefined,
    max_tokens: undefined,
    temperature: 0,
    top_p: undefined,
    frequency_penalty: undefined,
    presence_penalty: undefined,
    stop: undefined,
    seed: undefined,
    response_format: undefined,
    messages: [ [Object] ],
    tools: undefined,
    tool_choice: undefined,
    stream: true,
    stream_options: undefined
  },
  statusCode: undefined,
  responseHeaders: undefined,
  responseBody: undefined,
  isRetryable: true,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
 POST /api/chat 500 in 10474ms
```

**Comment by lgrammel** [comment]
Just tried the example and it works for me. Can you check if there is some sort of firewall preventing you from accessing deepseek?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily an environment-specific connectivity/support request, with no evidence that the AI SDK or its example is broken.

### Evidence
- The reported failure is an Undici connection timeout while contacting `https://api.deepseek.com/chat/completions`.
- The reporter explicitly suspects a network proxy and asks how to resolve the connectivity problem.
- A maintainer tested the same example successfully and suggested checking for a firewall blocking DeepSeek access.
