### ISSUE TITLE
Error attaching a pdf with experimental_attachments using OpenAI in useChat

### ISSUE THREAD

**Issue by bfioca** [vercel/ai#3356]
### Description

NextJS app router

Using useChat:

```
await handleSubmit(event, {
    experimental_attachments: fileAttachments,
});
```

The message with the file attachment (via a JSON.stringify console log):
```
{"role":"user","content":[{"type":"text","text":"Use this attachment as a starting point"},{"type":"file","data":"JVBERi0xLjQKJ ... VPRgo=","mimeType":"application/pdf"}]}
```

getting error back from openAI

```
⨯ APICallError [AI_APICallError]: Invalid type for 'messages[2].content[1]': expected an object, but got null instead.
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@ai-sdk+provider-utils@1.0.7_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:437:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async postToApi (webpack-internal:///(rsc)/./node_modules/.pnpm/@ai-sdk+provider-utils@1.0.7_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:344:28)
    at async OpenAIChatLanguageModel.doStream (webpack-internal:///(rsc)/./node_modules/.pnpm/@ai-sdk+openai@0.0.42_zod@3.23.8/node_modules/@ai-sdk/openai/dist/index.mjs:357:50)
    at async fn (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.4.18_openai@4.68.4_react@18.3.1_svelte@5.1.0_vue@3.5.12_zod@3.23.8/node_modules/ai/dist/index.mjs:3963:23)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.4.18_openai@4.68.4_react@18.3.1_svelte@5.1.0_vue@3.5.12_zod@3.23.8/node_modules/ai/dist/index.mjs:336:22)
    at async _retryWithExponentialBackoff (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.4.18_openai@4.68.4_react@18.3.1_svelte@5.1.0_vue@3.5.12_zod@3.23.8/node_modules/ai/dist/index.mjs:164:12)
    at async startStep (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.4.18_openai@4.68.4_react@18.3.1_svelte@5.1.0_vue@3.5.12_zod@3.23.8/node_modules/ai/dist/index.mjs:3928:13)
    at async fn (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.4.18_openai@4.68.4_react@18.3.1_svelte@5.1.0_vue@3.5.12_zod@3.23.8/node_modules/ai/dist/index.mjs:4004:11)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.4.18_openai@4.68.4_react@18.3.1_svelte@5.1.0_vue@3.5.12_zod@3.23.8/node_modules/ai/dist/index.mjs:336:22)
    at async POST (webpack-internal:///(rsc)/./app/api/chat/route.ts:58:18)
    at async /Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)
    at async ek.handle (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)
    at async doRender (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/brian/dev/psl/foodsci/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13) {
  cause: undefined,
  url: 'https://api.openai.com/v1/chat/completions',
  requestBodyValues: {
    model: 'gpt-4o',
    logit_bias: undefined,
    logprobs: undefined,
    top_logprobs: undefined,
    user: undefined,
    parallel_tool_calls: undefined,
    max_tokens: undefined,
    temperature: 0.1,
    top_p: undefined,
    frequency_penalty: undefined,
    presence_penalty: undefined,
    stop: undefined,
    seed: undefined,
    response_format: undefined,
    messages: [ [Object], [Object], [Object], [Object] ],
    tools: [ [Object] ],
    tool_choice: 'auto',
    stream: true,
    stream_options: { include_usage: true }
  },
  statusCode: 400,
  responseHeaders: {
    'access-control-expose-headers': 'X-Request-ID',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8d7c19230c6a13a2-SEA',
    connection: 'keep-alive',
    'content-length': '226',
    'content-type': 'application/json',
    date: 'Thu, 24 Oct 2024 18:40:57 GMT',
    'openai-organization': 'psl-5',
    'openai-processing-ms': '12',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '_cfuvid=_EGYlFv8iGjhLccKkA24lle7XKQLzoSsmo7xW4np0S4-1729795257132-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-ratelimit-limit-requests': '10000',
    'x-ratelimit-limit-tokens': '30000000',
    'x-ratelimit-remaining-requests': '9999',
    'x-ratelimit-remaining-tokens': '29995689',
    'x-ratelimit-reset-requests': '6ms',
    'x-ratelimit-reset-tokens': '8ms',
    'x-request-id': 'req_6ac72f17fa874242162cf1a37b75d89a'
  },
  responseBody: '{\n' +
    '  "error": {\n' +
    `    "message": "Invalid type for 'messages[2].content[1]': expected an object, but got null instead.",\n` +
    '    "type": "invalid_request_error",\n' +
    '    "param": "messages[2].content[1]",\n' +
    '    "code": "invalid_type"\n' +
    '  }\n' +
    '}',
  isRetryable: false,
  data: {
    error: {
      message: "Invalid type for 'messages[2].content[1]': expected an object, but got null instead.",
      type: 'invalid_request_error',
      param: 'messages[2].content[1]',
      code: 'invalid_type'
    }
  },
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
```

**Comment by bfioca** [comment]
Realized that pdfs aren't supported as inputs to openAI 😅

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a self-resolved support/compatibility issue caused by using an unsupported OpenAI input type, not a demonstrated AI SDK defect or explicit feature request.

### Evidence
- The report shows OpenAI rejecting a PDF attachment sent through `experimental_attachments`.
- The reporter later clarified that PDF inputs are not supported by OpenAI and did not request SDK support or a behavior change.
