### ISSUE TITLE
 Message Interruption When Using useChat with @ai-sdk/anthropic and Asynchronous Tools, While Normal Chat Works Fine

### ISSUE THREAD

**Issue by Abdurihim** [vercel/ai#3709]
### Description

I'm encountering an issue when using the useChat function along with @ai-sdk/anthropic in my project. The normal chat functionality seems to work without any problems. However, when attempting to use asynchronous tools within the chat, the message flow gets interrupted.

### Code example

`

    const result = await streamText({
      system: systemPrompt,
      model: model.model,
      temperature: 0,
      messages,
      maxTokens: model.maxTokens,
      tools,
      toolChoice: "auto",
      experimental_toolCallStreaming: true,
      maxRetries: 3,
      abortSignal: req.signal,

      onFinish(event) {
        console.log("对话结束原因:", event.finishReason);
        console.log("对话使用信息:", event.usage);
      },
      onStepFinish(event) {
        console.log("对话结束原因:", event.finishReason);
      },
    });
    
    
    
    
    
    
    
      const {
    messages,
    input,
    handleInputChange,
    handleSubmit,
    isLoading,
    stop,
    addToolResult,
  } = useChat({
    api: "/api/chat",
    body: {
      customData: {
        developmentEnv: envSelection.developmentEnv,
        selectedStack: envSelection.selectedStack,
        languageModel: envSelection.languageModel,
      },
    },
    maxSteps: 100,
    async onToolCall({ toolCall }) {
      console.log("onToolCall", toolCall);

      // 根据环境选择对应的工具处理器
      const handlers =
        envSelection.developmentEnv === DevelopmentEnv.ReactLive
          ? toolHandlers
          : envSelection.developmentEnv === DevelopmentEnv.Local
          ? previewToolHandlers
          : null;

      if (handlers) {
        const handler = handlers[
          toolCall.toolName as keyof typeof handlers
        ] as (args: any) => Promise<any>;
        if (handler) {
          return await handler(toolCall.args);
        }
      }
    },
    onError: (error) => {
      console.log("Chat error:", error);
      toast({
        variant: "destructive",
        title: "错误提示",
        description: error.message || "发生未知错误，请稍后重试",
      });
    },
    // 添加onFinish回调
    onFinish: async (message) => {},
  });
`

### AI provider

@ai-sdk/anthropi  ^0.0.54

### Additional context

Chat error: Error
    at processDataProtocolResponse (index.mjs:736:1)
    at async callChatApi (index.mjs:1019:1)
    at async getStreamedResponse (index.mjs:226:1)
    at async processChatStream (index.mjs:1231:1)
    at async eval (index.mjs:347:1)
    at async eval (index.mjs:398:1)
    at async eval (index.mjs:398:1)
    at async eval (index.mjs:398:1)
    at async eval (index.mjs:398:1)
    at async eval (index.mjs:398:1)
    at async eval (index.mjs:398:1)

**Comment by blobgetblob** [comment]
hello any update on this?

**Comment by lgrammel** [comment]
I have tested the tool calling code with Anthropic. Here is an updated version of the example which works for me:

- https://github.com/vercel/ai/blob/main/examples/next-openai/app/api/use-chat-tools/route.ts
- https://github.com/vercel/ai/tree/main/examples/next-openai/app/use-chat-tools

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This is framed as a concrete runtime failure in existing `useChat` and Anthropic tool-calling behavior. The successful maintainer test reduces certainty but does not clearly establish that the report is only a usage question.

### Evidence
- The reporter says `useChat` message streaming is interrupted when asynchronous Anthropic tool calls are used and provides a `processDataProtocolResponse` error stack.
- Normal chat reportedly works, isolating the failure to tool-call handling.
- A maintainer could not reproduce the failure and linked an updated working tool-calling example.
