### ISSUE TITLE
Gemini: GenerateContentRequest.contents[...].parts: contents.parts must not be empty

### ISSUE THREAD

**Issue by capkakitiga** [vercel/ai#3775]
### Description

⨯ Error [AI_APICallError]: * GenerateContentRequest.contents[2].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[5].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[8].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[11].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[14].parts: contents.parts must not be empty.

    at <unknown> (/var/task/.next/server/app/(chat)/api/chat/route.js:36:4984)
    at async em (/var/task/.next/server/app/(chat)/api/chat/route.js:36:2111)
    at async ex.doStream (/var/task/.next/server/app/(chat)/api/chat/route.js:36:10963)
    at async fn (/var/task/.next/server/app/(chat)/api/chat/route.js:44:45816)
    at async (/var/task/.next/server/app/(chat)/api/chat/route.js:44:3458)
    at async tc (/var/task/.next/server/app/(chat)/api/chat/route.js:44:1504)
    at async s (/var/task/.next/server/app/(chat)/api/chat/route.js:44:44955)
    at async fn (/var/task/.next/server/app/(chat)/api/chat/route.js:44:48173)
    at async (/var/task/.next/server/app/(chat)/api/chat/route.js:44:3458) {
  cause: undefined,
  url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse',
  requestBodyValues: [Object],
  statusCode: 400,
  responseHeaders: [Object],
  responseBody: '{\n' +
    '  "error": {\n' +
    '    "code": 400,\n' +
    '    "message": "* GenerateContentRequest.contents[2].parts: contents.parts must not be empty.\\n* GenerateContentRequest.contents[5].parts: contents.parts must not be empty.\\n* GenerateContentRequest.contents[8].parts: contents.parts must not be empty.\\n* GenerateContentRequest.contents[11].parts: contents.parts must not be empty.\\n* GenerateContentRequest.contents[14].parts: contents.parts must not be empty.\\n",\n' +
    '    "status": "INVALID_ARGUMENT"\n' +
    '  }\n' +
    '}\n',
  isRetryable: false,
  data: [Object]
}

### AI provider

@ai-sdk/google 0.0.23

### Additional context

Idk whats wrong with this

**Comment by lgrammel** [comment]
`@ai-sdk/google@0.0.23` is fairly old. Can you update to `1.0.0` and see if the error still happens?

**Comment by capkakitiga** [comment]
> `@ai-sdk/google@0.0.23` is fairly old. Can you update to `1.0.0` and see if the error still happens?

sorry my bad it was  "@ai-sdk/google": "^1.0.0",

**Comment by capkakitiga** [comment]
[payload_gemini_error.json](https://github.com/user-attachments/files/17817496/payload_gemini_error.json)

here is the payload

**Comment by hossdar** [comment]
Confirming that with the latest release "@ai-sdk/google": "^1.0.4" and "ai": "^4.0.9".

I'm getting error when switching to another model **in the same chat**, only if a Gemini model is involved. 
No errors when switching back and forth among Grok or OpenAI models.. run smoothly.

**Comment by michaelwlt** [comment]
Experiencing a similar problem when trying to continue chats with gemini after logging in and out using the vercel ai chatbot template. Error is present with "@ai-sdk/google": "^1.0.10" and  "ai": "^4.0.16"
```
error code: 1)
    56 |       return {
    57 |         responseHeaders,
  > 58 |         value: new APICallError({
       |               ^
    59 |           message: errorToMessage(parsedError),
    60 |           url,
    61 |           requestBodyValues, {
    cause: undefined,
    url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:streamGenerateContent?alt=sse',
    requestBodyValues: [Object],
    statusCode: 400,
    responseHeaders: [Object],
    responseBody: '{\n' +
      '  "error": {\n' +
      '    "code": 400,\n' +
      '    "message": "* GenerateContentRequest.contents[2].parts: contents.parts must not be empty.\\n",\n' +
      '    "status": "INVALID_ARGUMENT"\n' +
      '  }\n' +
      '}\n',
    isRetryable: false,
    data: [Object]
  }
  The data stream is hanging. Did you forget to close it with `data.close()`?
```

**Comment by nachodeh** [comment]
@lgrammel still seeing this issue with `@ai-sdk/google": "^1.1.14`
Does not happen with openai model provider

**Comment by grmkris** [comment]
same here

**Comment by lgrammel** [comment]
A fix was landed in 1.1.16:

```
## 1.1.16

### Patch Changes

- 1b2e2a0: fix (provider/google): add resilience against undefined parts
```

https://github.com/vercel/ai/pull/4934

Please try that version or newer and report back if you still run into the issue.

**Comment by nachodeh** [comment]
@lgrammel still seeing the issue on "@ai-sdk/google": "^1.1.18"

**Comment by lgrammel** [comment]
@nachodeh what is the exact error that you are getting?

**Comment by montecruiseto** [comment]
Getting the same: 

Server error: * GenerateContentRequest.contents[0].parts: contents.parts must not be empty.

I'm on  "@ai-sdk/google": "^1.1.25"

**Comment by nachodeh** [comment]
@lgrammel why would that throw an error for google but no error for openai model with the same prompt, context, etc? Surely it can't be the prompt.

Here is the code I'm using:
```
const result = streamText({
        model: google("gemini-2.0-flash-001"),
        system: generateChatSystemPrompt2(),
        messages,
        experimental_generateMessageId: () => id(),
        async onError({ error }) {
            console.error("ERROR", error)
        },
        async onFinish({ response }) {
            console.log("FINISH", response)
        },
    })
```

This is what the prompt looks like
```
export const generateChatSystemPrompt2 = () => {
    return `
Say hello to the user.
`
}
```

Dependencies
```
"@ai-sdk/google": "^1.1.18",
"@ai-sdk/openai": "^1.2.0",
```

And worth noting, even if pass an empty array as messages, this still fails. This is the latest error message:
```
ERROR Error [AI_APICallError]: * GenerateContentRequest.contents: contents is not specified

    at async (../src/index.ts:199:27)
    at async FallbackModel.retry (../src/index.ts:147:23) {
  cause: undefined,
  url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-001:streamGenerateContent?alt=sse',
  requestBodyValues: [Object],
  statusCode: 400,
  responseHeaders: [Object],
  responseBody: '{\n' +
    '  "error": {\n' +
    '    "code": 400,\n' +
    '    "message": "* GenerateContentRequest.contents: contents is not specified\\n",\n' +
    '    "status": "INVALID_ARGUMENT"\n' +
    '  }\n' +
    '}\n',
  isRetryable: false,
  data: [Object]
}
```

**Comment by lgrammel** [comment]
I need to see the messages. Can anyone provide the messages so I can debug the issue? Thank you.

**Comment by nachodeh** [comment]
> I need to see the messages. Can anyone provide the messages so I can debug the issue? Thank you.

Hey @lgrammel, even when I don't pass messages, the following fails with the same error as above. The messages are not the culprit:

```
const emptyMessages: any[] = []
const result = streamText({
    model: google("gemini-2.0-flash-001"),
    system: generateChatSystemPrompt2(),
    async onError({ error }) {
        console.error("ERROR", error)
    },
    async onFinish({ response }) {
        console.log("FINISH", response)
    },
})
result.consumeStream() // Finish the stream even if the client disconnects
return result.toDataStreamResponse()
```

**Comment by lgrammel** [comment]
@nachodeh you must pass in messages or a prompt. An empty messages array will not suffice.

```
  const result = streamText({
    model: google('gemini-2.0-flash-001'),
    system: '\nSay hello to the user.\n',
    prompt: 'Greet the user',
    async onError({ error }) {
      console.error('ERROR', error);
    },
  });
```

The above works for me, I still could not reproduce 

```
ERROR Error [AI_APICallError]: * GenerateContentRequest.contents[3].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[5].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[7].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[9].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[15].parts: contents.parts must not be empty.
* GenerateContentRequest.contents[17].parts: contents.parts must not be empty.
```

which is a differnet error from "contents not specified."

**Comment by lgrammel** [comment]
Add a check for empty messages arrays to catch that early.

Do you have example messages for the `GenerateContentRequest.contents[5].parts: contents.parts must not be empty.` error?

**Comment by nachodeh** [comment]
Cool, I deleted the whole thread and not seeing the issue now. Curious as to why openai was working but not google

**Comment by lgrammel** [comment]
Google might be stricter on the input validation. Keeping this open in case someone else finds examples that help w/ reproduction.

**Comment by KenjiPcx** [comment]
I might be able to help with this, I was using the new packages ai-sdk/google@1.2.3 and ai@4.2.6, and using the code from the vercel ai chatbot template, for some reason all my messages loaded from the database result in the content having an empty string, all the text is within the parts array instead

**Comment by KenjiPcx** [comment]
If your app is using some code like this, the empty content string is the culprit
```
function convertToUIMessages(messages: Array<DBMessage>): Array<UIMessage> {
    return messages.map((message) => ({
      id: message.id,
      parts: message.parts as UIMessage['parts'],
      role: message.role as UIMessage['role'],
      // Note: content will soon be deprecated in @ai-sdk/react
      content: '',
      createdAt: message.createdAt,
      experimental_attachments:
        (message.attachments as Array<Attachment>) ?? [],
    }));
  }
```

**Comment by lgrammel** [comment]
@KenjiPcx do you have a expanded UI message array (JSON), ideally minimal but reproducing the error that I could use for testing? I suspect the error has to do with how `convertToCoreMessages` converts in the case content is empty but parts are present.

**Comment by lgrammel** [comment]
Please try `ai@4.2.7`

**Comment by KenjiPcx** [comment]
Hi @lgrammel, sorry for the late reply 😅, but looks like you've figured it out, for backwards compatibility, should we stop putting text in the content field of a message?

**Comment by lgrammel** [comment]
@KenjiPcx it should work either way but heads up that content will most likely be removed in AI SDK 5

**Comment by martian7777** [comment]
<img width="785" height="152" alt="Image" src="https://github.com/user-attachments/assets/77a07919-8ac3-4df3-ab42-e1f1ecaffdce" />

The issue is still there with gemini models in langflow.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports incorrect message conversion that creates invalid Gemini payloads and causes API calls to fail. The maintainer's patch/version guidance further supports that this was an SDK defect rather than a feature request or documentation issue.

### Evidence
- Gemini requests fail with HTTP 400 because the SDK produces `contents` entries whose `parts` are empty.
- Multiple users reproduced the failure across current `@ai-sdk/google` releases, while the same conversations worked with OpenAI.
- The failure was narrowed to conversion of UI messages where `content` is empty but valid text exists in `parts`; the maintainer suspected `convertToCoreMessages` and directed users to try the patched `ai@4.2.7`.
