### ISSUE TITLE
Groq provider streamObject fails with AI_TypeValidationError and doesn't produce results

### ISSUE THREAD

**Issue by e-simpson** [vercel/ai#4047]
### Description

Unable to use streaming object functionality with the Groq provider `1.0.7` on AI SDK `4.0.13`.

```
Uncaught (in promise) AI_TypeValidationError: Type validation failed: Value: undefined.
Error message: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at _TypeValidationError.wrap (type-validation-error.ts:49:9)
    at safeValidateTypes (validate-types.ts:63:34)
    at Object.validateFinalResult (output-strategy.ts:86:12)
    at Object.transform (stream-object.ts:802:38)Caused by: ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at get error (index.mjs:587:31)
    at Object.validate (schema.ts:81:45)
    at safeValidateTypes (validate-types.ts:55:30)
    at Object.validateFinalResult (output-strategy.ts:86:12)
    at Object.transform (stream-object.ts:802:38)
```

### Code example

```JSX
import { createGroq } from '@ai-sdk/groq';
import { streamObject } from 'ai';
import { z } from 'zod';

const groq = createGroq();

const { partialObjectStream, object, usage } = streamObject({
    model: groq('llama-3.3-70b-versatile'),
    schema: z.object({
        recipe: z.object({
            name: z.string(),
            ingredients: z.array(z.string()),
            steps: z.array(z.string()),
        }),
     }),
     prompt: 'Generate a lasagna recipe.'
});

for await (const partialObject of partialObjectStream) {
     console.log("streaming", partialObject, partialObjectStream);
}
console.log("full object", object, usage);
```

### AI provider

@ai-sdk/groq v1.0.7

### Additional context

GenerateObject works fine.

I tried using the `1.0.7` openai provider and the Groq openai API as the baseURL, and found that I can get streamObject to produce the result, but no streaming behaviour.

Tests:
- groq provider w/ `streamObject` & `llama-3.3-70b-versatile` model -> `ERROR`
- groq provider w/ `generateObject` & `llama-3.3-70b-versatile` model -> `WORKS`
- openai provider w/ `streamObject` & `llama-3.3-70b-versatile` model -> `WORKS` but no streaming behaviour
- openai provider w/ `generateObject` & `llama-3.3-70b-versatile` model -> `WORKS`

**Comment by e-simpson** [comment]
The [groq provider page](https://sdk.vercel.ai/providers/ai-sdk-providers/groq) lists that tool streaming is supported but I'm not sure it is. I can't even seem to get it working on the Groq typescript SDK itself. Non-streaming works fine there too.

**Comment by lgrammel** [comment]
Can you try with 

```
model: groq('llama-3.1-70b-versatile')
``` 

I just checked with llama-3.3 vs 3.1, and only 3.1 works. Currently unclear if it's a groq model limitation or a provider issue.

**Comment by lgrammel** [comment]
The explanation for the observed behavior:
- generateObject / groq -> uses groq structured outputs (option only available for non-streaming use per groq api)
- generateObject / openai -> uses tool call
- streamObject / groq -> no structured output enforcements leads to breakage; recommend prompt engineering
- streamObject / openai -> uses tool call (but tool call is not streamed)

**Comment by Kae7in** [comment]
> The explanation for the observed behavior:
> 
> * generateObject / groq -> uses groq structured outputs (option only available for non-streaming use per groq api)
> * generateObject / openai -> uses tool call
> * streamObject / groq -> no structured output enforcements leads to breakage; recommend prompt engineering
> * streamObject / openai -> uses tool call (but tool call is not streamed)
> 
> You can enable tool mode on the groq provider with `mode: 'tool'`:
> 
>   const result = streamObject({
>     model: groq('llama-3.3-70b-versatile'),
>     mode: 'tool',
>     // ...
>    })

thank you! this solved my issue

**Comment by gr2m** [comment]
I assume this is resolved? Please open a new issue if theproblem persists

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was resolved as a provider/model capability and configuration limitation rather than a defect in the AI SDK. The issue primarily functioned as a support request with a working configuration solution.

### Evidence
- Groq structured outputs are only available for non-streaming requests, so the default `streamObject` path lacks schema enforcement.
- A maintainer recommended `mode: 'tool'` for this model and provider combination.
- The reporter confirmed that using tool mode solved the issue, and no SDK code change was identified as necessary.
