### ISSUE TITLE
Still getting "The security token included in the request is invalid" using Bedrock

### ISSUE THREAD

**Issue by PierrickLozach** [vercel/ai#4163]
### Description

When I try to use `createAmazonBedrock()`, I get `The security token included in the request is invalid` when using `generateText`.

I have checked my credentials again and use `''` for sessionToken as recommended.

I also used `bedrockOptions` to make sure it overwrites other settings but no luck.

I get this error:

```console
🤖 Chat request received.
AWS_REGION: xxxx (hidden)
AWS_ACCESS_KEY_ID: xxxx (hidden)
AWS_SECRET_ACCESS_KEY: xxxx (hidden)
 ⨯ UnrecognizedClientException: The security token included in the request is invalid.
    at async POST (apps/app/app/api/chat/route.ts:19:19)
  17 |
  18 |   const model = provider('anthropic.claude-3-5-sonnet-20240620-v1:0');
> 19 |   const { text } = await generateText({
     |                   ^
  20 |     model,
  21 |     prompt: 'Write a vegetarian lasagna recipe for 4 people.',
  22 |   }); {
  '$fault': 'client',
  '$metadata': [Object]
}
 ⨯ UnrecognizedClientException: The security token included in the request is invalid.
    at async POST (apps/app/app/api/chat/route.ts:19:19)
  17 |
  18 |   const model = provider('anthropic.claude-3-5-sonnet-20240620-v1:0');
> 19 |   const { text } = await generateText({
     |                   ^
  20 |     model,
  21 |     prompt: 'Write a vegetarian lasagna recipe for 4 people.',
  22 |   }); {
  '$fault': 'client',
  '$metadata': [Object]
```

### Code example

provider:

```
import { createAmazonBedrock } from '@ai-sdk/amazon-bedrock';
import { env } from '@repo/env';

export const provider = createAmazonBedrock({
  region: env.AWS_REGION,
  accessKeyId: env.AWS_ACCESS_KEY_ID,
  secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
  sessionToken: '',
  bedrockOptions: {
    region: env.AWS_REGION,
    credentials: {
      accessKeyId: env.AWS_ACCESS_KEY_ID,
      secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
      sessionToken: '',
    },
  },
});
```

Chat Route:

```
import { streamText } from '@repo/ai';
import { provider } from '@repo/ai/lib/provider';
import { log } from '@repo/observability/log';
import { generateText } from '@repo/ai';
import { env } from '@repo/env';

export const POST = async (req: Request) => {
  const body = await req.json();

  //log.info('🤖 Chat request received.', { body });
  log.info('🤖 Chat request received.');
  const { messages } = body;

  log.info(`AWS_REGION: ${env.AWS_REGION}`)
  log.info(`AWS_ACCESS_KEY_ID: ${env.AWS_ACCESS_KEY_ID}`)
  log.info(`AWS_SECRET_ACCESS_KEY: ${env.AWS_SECRET_ACCESS_KEY}`)

  const model = provider('anthropic.claude-3-5-sonnet-20240620-v1:0');
  const { text } = await generateText({
    model,
    prompt: 'Write a vegetarian lasagna recipe for 4 people.',
  });

  console.log(text);

  log.info('🤖 Generating response...');
  const result = streamText({
    model,
    system: 'You are a helpful assistant.',
    messages,
  });

  log.info('🤖 Streaming response...');
  return result.toDataStreamResponse();
};
```

### AI provider

@ai-sdk/amazon-bedrock v1.0.5

**Comment by PierrickLozach** [comment]
My credentials were indeed incorrect... damn, wasted almost an entire days on this. Thanks again for the response!

**Comment by nicoalbanese** [comment]
No worries-  happy you got it sorted!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a configuration/support issue caused by invalid credentials, not a failure or requested change in the AI SDK.

### Evidence
- The maintainer could not reproduce the error with the provided Bedrock settings and reported that they worked as expected.
- The reporter later confirmed that their AWS credentials were incorrect and that the issue was resolved.
