### ISSUE TITLE
Error: "assistant_control_data" parts expect an object with a "threadId" and "messageId"

### ISSUE THREAD

**Issue by MwSpaceLLC** [vercel/ai#4189]
### Description

we have copy, pasted usage on: https://sdk.vercel.ai/docs/ai-sdk-ui/openai-assistants

the log server, message assistant complete, but client sho onError: => 

`Error: "assistant_control_data" parts expect an object with a "threadId" and "messageId" property.
    at Object.parse (index.mjs:47:1)
    at parseAssistantStreamPart (index.mjs:109:1)
    at Array.map (<anonymous>)
    at processAssistantStream (index.mjs:1275:76)
    at async append (index.mjs:75:1)
    at async handleSubmit (ChatComponentAssistant.jsx:75:9)
    at async handleChooseQuickAction (ChatComponentAssistant.jsx:135:9)
    `

### Code example

> Client code

```js
    const {messages, input, status, isLoading: isLoadingRequest, setInput, append} = useAssistant({
        api: '/api/main/stream',
        // in: messagesData,
        // onToolCall: () => setIsGenerating(true),
        // onFinish: () => setIsGenerating(false),
        // onResponse: () => {
        //     setIsGenerating(true); // start loading generation
        //     // setIsFirstLoading(false) // stop first loading
        // },
        onError: (error) => {
            console.log(error)
            alert(error.message, {variant: 'danger'})
        },
    });
```

> Server Side:

```js
async function streamFromSdkAi(threadId, messageId, ASSISTANT_MESSAGE, openai, user, model, filterThread) {
    console.info('streamFromSdkAi:assistant:stream', threadId, messageId);

    // const openai = createOpenAI({apiKey: user.OpenAiToken})

    return AssistantResponse({threadId, messageId},
        async ({forwardStream, sendDataMessage}) => {

            // Run the assistant on the thread
            const runStream = openai.beta.threads.runs.stream(threadId, ASSISTANT_MESSAGE);

            // forward run status would stream message deltas
            let runResult = await forwardStream(runStream);

            // Quando lo stream è completato
            if (runResult.status === 'completed') {

                // Recupera il messaggio completo
                const messages = await openai.beta.threads.messages.list(threadId);
                const lastMessage = messages.data[0]; // L'ultimo messaggio

                // async update thread
                modelThreads.updateOne(filterThread, {
                    $push: {
                        messages: {
                            role: 'assistant',
                            content: lastMessage.content[0].text.value,
                            timestamp: new Date()
                        }
                    }
                })
            }

            // status can be: queued, in_progress, requires_action, cancelling, cancelled, failed, completed, or expired
            while (
                runResult?.status === 'requires_action' &&
                runResult.required_action?.type === 'submit_tool_outputs'
                ) {
                const tool_outputs =
                    runResult.required_action.submit_tool_outputs.tool_calls.map(
                        (toolCall) => {
                            const parameters = JSON.parse(toolCall.function.arguments);

                            switch (toolCall.function.name) {
                                // configure your tool calls here

                                default:
                                    throw new Error(
                                        `Unknown tool call function: ${toolCall.function.name}`,
                                    );
                            }
                        },
                    );

                runResult = await forwardStream(
                    openai.beta.threads.runs.submitToolOutputsStream(
                        threadId,
                        runResult.id,
                        {tool_outputs},
                    ),
                );
            }
        },
    );

}
```

### AI provider

"@ai-sdk/openai": "^1.0.10",

### Additional context

run process send, work, assistant log correctly..

i think u must add also, initialMessages on, (for our spot is the best)

> helper

```ts
type UseAssistantOptions = {
    /**
     * The API endpoint that accepts a `{ threadId: string | null; message: string; }` object and returns an `AssistantResponse` stream.
     * The threadId refers to an existing thread with messages (or is `null` to create a new thread).
     * The message is the next message that should be appended to the thread and sent to the assistant.
     */
    api: string;
    /**
     * An optional string that represents the ID of an existing thread.
     * If not provided, a new thread will be created.
     */
    threadId?: string;
    /**
     * An optional literal that sets the mode of credentials to be used on the request.
     * Defaults to "same-origin".
     */
    credentials?: RequestCredentials;
    /**
     * An optional object of headers to be passed to the API endpoint.
     */
    headers?: Record<string, string> | Headers;
    /**
     * An optional, additional body object to be passed to the API endpoint.
     */
    body?: object;
    /**
     * An optional callback that will be called when the assistant encounters an error.
     */
    onError?: (error: Error) => void;
    /**
  Custom fetch implementation. You can use it as a middleware to intercept requests,
  or to provide a custom fetch implementation for e.g. testing.
      */
    fetch?: FetchFunction;
};
```

**Comment by MwSpaceLLC** [comment]
> sorry, solved, we have wrong parameter on `messageId` on:

`streamFromSdkAi(threadId, messageId, ASSISTANT_MESSAGE, openai, user, model, filterThread)`

now work fine. Tnks AI Team ! 🥰

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The failure was caused by application code rather than broken SDK behavior, and no documentation or product change is requested after resolution.

### Evidence
- The reported stream parsing error occurred while passing an incorrect `messageId` parameter.
- The reporter confirmed that correcting the parameter resolved the issue and the SDK now works.
