### ISSUE TITLE
Using in NodeJS throw ReferenceError: Response is not defined

### ISSUE THREAD

**Issue by chengsokdara** [vercel/ai#491]
I am using the package in an express app.

When trying to import anything from 'ai' this is thrown
```
[project]/node_modules/ai/dist/index.js:480
var StreamingTextResponse = class extends Response {
                            ^
ReferenceError: Response is not defined
    at Object.<anonymous> ([project]/node_modules/ai/dist/index.js:480:29)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.require.extensions.<computed> [as .js] ([project]/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> ([project]/src/routes/[route].ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
```

Checking the source code.
`packages/core/streams/streaming-text-response.ts`

`line 8: export class StreamingTextResponse extends Response {`

Is this package only can be use in NextJs?

**Comment by MaxLeiter** [comment]
>Is this package only can be use in NextJs?
You can use `streamToResponse`: https://sdk.vercel.ai/docs/api-reference/stream-to-response#example-nodejs-http-server

**Comment by chengsokdara** [comment]
@MaxLeiter I'm sorry I didn't make my question clear, it still crash on Express environment
This time I have included a reproducible example on CodeSandbox, please have a look.

[https://codesandbox.io/p/sandbox/busy-minsky-rfhxwx](https://codesandbox.io/p/sandbox/busy-minsky-rfhxwx)

**Comment by MaxLeiter** [comment]
@chengsokdara can you ensure you're using node 18?


Thanks @rpidburachynskyi for sharing that.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an environment/version support question rather than a failure in a supported runtime; the reported error is addressed by using the documented Node.js 18 version.

### Evidence
- Importing `ai` in an Express app throws because the global `Response` class is unavailable.
- A commenter resolved the error by switching to Node.js 18, as required by the documentation.
- The maintainer asked the reporter to verify that Node.js 18 was being used.
